[E 190215 15:59:26 web:1670] Uncaught exception DELETE /api/v1/projects (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='DELETE', uri='/api/v1/projects', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 86, in delete
        return self.set_status(403, {'reason': 'fiald'})
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 326, in set_status
        self._reason = escape.native_str(reason)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/escape.py", line 215, in to_unicode
        "Expected bytes, unicode, or None; got %r" % type(value)
    TypeError: Expected bytes, unicode, or None; got <class 'dict'>
[E 190215 15:59:26 web:2162] 500 DELETE /api/v1/projects (::1) 44.17ms
[E 190215 16:12:58 web:1670] Uncaught exception GET /api/v1/projects (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/projects', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 37, in get
        params, offset, limit, ordering = prep_params(arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 130, in prep_params
        ordering = params.pop('ordering')
    KeyError: 'ordering'
[E 190215 16:12:58 web:2162] 500 GET /api/v1/projects (::1) 7556.46ms
[E 190215 16:19:09 web:1670] Uncaught exception GET /api/v1/projects (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/projects', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 44, in get
        self.finish(resp)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1025, in finish
        self.write(chunk)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 744, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 190215 16:19:09 web:2162] 500 GET /api/v1/projects (::1) 13216.46ms
[E 190215 16:22:40 web:1670] Uncaught exception GET /api/v1/projects (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/projects', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 44, in get
        self.finish(resp)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1025, in finish
        self.write(chunk)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 744, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 190215 16:22:40 web:2162] 500 GET /api/v1/projects (::1) 181863.08ms
[W 190215 16:31:45 web:2162] 401 DELETE /api/v1/projects (::1) 13608.59ms
[W 190215 16:32:40 web:2162] 401 DELETE /api/v1/projects (::1) 2912.74ms
[W 190215 16:32:51 web:2162] 403 DELETE /api/v1/projects (::1) 1863.08ms
[W 190215 16:33:05 web:2162] 403 DELETE /api/v1/projects (::1) 2697.81ms
