[W 190214 12:00:15 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 12:00:15 CST)" skipped: maximum number of running instances reached (1)
[W 190214 12:00:20 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 12:00:20 CST)" skipped: maximum number of running instances reached (1)
[W 190214 12:00:30 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 12:00:30 CST)" skipped: maximum number of running instances reached (1)
[W 190214 12:00:35 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 12:00:35 CST)" skipped: maximum number of running instances reached (1)
[W 190214 12:00:45 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 12:00:45 CST)" skipped: maximum number of running instances reached (1)
[W 190214 12:01:09 handler:36] ['baidu', 'sina']
[W 190214 13:17:02 handler:36] ['baidu', 'sina']
[W 190214 13:17:04 handler:36] ['baidu', 'sina']
[W 190214 13:17:05 handler:36] ['baidu', 'sina']
[W 190214 13:17:06 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:06 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:07 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:07 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:08 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:08 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:09 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:09 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:10 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:10 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:11 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:11 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:12 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:12 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:13 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:13 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:14 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:14 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:15 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:15 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:20 handler:36] ['baidu', 'sina']
[W 190214 13:17:21 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:21 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:22 handler:36] ['baidu', 'sina']
[W 190214 13:17:22 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:22 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:23 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:23 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:24 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:24 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:25 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:25 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:26 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:26 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:27 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:27 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:28 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:28 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:29 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:29 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:30 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:30 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:36 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:36 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:37 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:37 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:38 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:38 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:39 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:39 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:40 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:40 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:41 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:41 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:42 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:42 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:43 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:43 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:44 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:44 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:45 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:45 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:46 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:46 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:48 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:48 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:52 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:52 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:54 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:54 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:55 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:55 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:56 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:56 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:57 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:57 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:58 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:58 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:17:59 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:17:59 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:18:00 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:18:00 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:23:03 handler:36] ['baidu', 'sina']
[W 190214 13:23:46 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:23:46 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:23:51 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:23:51 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:23:57 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:23:57 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:01 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:01 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:02 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:02 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:06 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:06 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:11 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:11 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:12 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:12 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:17 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:17 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:21 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:21 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:26 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:26 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:27 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:27 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:32 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:32 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:36 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:36 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:41 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:41 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:42 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:42 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:47 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:47 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:51 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:51 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:56 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:56 CST)" skipped: maximum number of running instances reached (1)
[W 190214 13:24:57 base:975] Execution of job "execute_task (trigger: interval[0:00:05], next run at: 2019-02-14 13:24:57 CST)" skipped: maximum number of running instances reached (1)
[E 190214 13:26:56 web:1670] Uncaught exception GET /api/v1/schedulers (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 108, in get
        filters = ast.literal_eval(arguments.filters.data)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 46, in literal_eval
        node_or_string = parse(node_or_string, mode='eval')
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 0
        
        ^
    SyntaxError: unexpected EOF while parsing
[E 190214 13:26:56 web:2162] 500 GET /api/v1/schedulers (::1) 37.50ms
[E 190214 13:27:05 web:1670] Uncaught exception GET /api/v1/schedulers (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 108, in get
        filters = ast.literal_eval(arguments.filters.data)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 46, in literal_eval
        node_or_string = parse(node_or_string, mode='eval')
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 0
        
        ^
    SyntaxError: unexpected EOF while parsing
[E 190214 13:27:05 web:2162] 500 GET /api/v1/schedulers (::1) 14.30ms
[E 190214 13:27:53 web:1670] Uncaught exception GET /api/v1/schedulers (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 111, in get
        res = await Schedulers.filter(**filters).limit(limit).order_by(order)
    TypeError: filter() argument after ** must be a mapping, not NoneType
[E 190214 13:27:53 web:2162] 500 GET /api/v1/schedulers (::1) 6973.71ms
[E 190214 13:31:45 web:1670] Uncaught exception GET /api/v1/schedulers?filters=%7B%27id%27%3E1%7D (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers?filters=%7B%27id%27%3E1%7D', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 108, in get
        filters = ast.literal_eval(arguments.filters.data) if arguments.filters.data else {}
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 91, in literal_eval
        return _convert(node_or_string)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 76, in _convert
        return set(map(_convert, node.elts))
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 90, in _convert
        return _convert_signed_num(node)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 63, in _convert_signed_num
        return _convert_num(node)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/ast.py", line 55, in _convert_num
        raise ValueError('malformed node or string: ' + repr(node))
    ValueError: malformed node or string: <_ast.Compare object at 0x7ff76c70f8d0>
[E 190214 13:31:45 web:2162] 500 GET /api/v1/schedulers?filters=%7B%27id%27%3E1%7D (::1) 6.13ms
[E 190214 13:33:06 web:1670] Uncaught exception GET /api/v1/schedulers?filters=%27id%3E2%27 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers?filters=%27id%3E2%27', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 113, in get
        res = await Schedulers.filter(*filters).limit(limit).order_by(order)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 276, in filter
        return QuerySet(cls).filter(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 160, in filter
        return self._filter_or_exclude(negate=False, *args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 136, in _filter_or_exclude
        raise TypeError('expected Q objects as args')
    TypeError: expected Q objects as args
[E 190214 13:33:06 web:2162] 500 GET /api/v1/schedulers?filters=%27id%3E2%27 (::1) 4628.74ms
[E 190214 13:33:52 web:1670] Uncaught exception GET /api/v1/schedulers?filters=%27id%3E2%27 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/api/v1/schedulers?filters=%27id%3E2%27', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 112, in get
        res = await Schedulers.filter(*filters).limit(limit).order_by(order)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 276, in filter
        return QuerySet(cls).filter(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 160, in filter
        return self._filter_or_exclude(negate=False, *args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 136, in _filter_or_exclude
        raise TypeError('expected Q objects as args')
    TypeError: expected Q objects as args
[E 190214 13:33:52 web:2162] 500 GET /api/v1/schedulers?filters=%27id%3E2%27 (::1) 9142.01ms
[E 190214 13:58:48 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 116, in get
        res = await Schedulers.filter(*filters).limit(limit).order_by(ordering)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 276, in filter
        return QuerySet(cls).filter(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 160, in filter
        return self._filter_or_exclude(negate=False, *args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 136, in _filter_or_exclude
        raise TypeError('expected Q objects as args')
    TypeError: expected Q objects as args
[E 190214 13:58:48 web:2162] 500 GET /api/v1/schedulers?spider=sina (::1) 93.33ms
[E 190214 14:06:31 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina&status=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina&status=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 113, in get
        for i, value in arg.items():
    RuntimeError: dictionary changed size during iteration
[E 190214 14:06:31 web:2162] 500 GET /api/v1/schedulers?spider=sina&status=1 (::1) 5053.71ms
[E 190214 14:08:15 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina&status=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina&status=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 113, in get
        for i, value in arg.items():
    RuntimeError: dictionary changed size during iteration
[E 190214 14:08:15 web:2162] 500 GET /api/v1/schedulers?spider=sina&status=1 (::1) 12896.09ms
[E 190214 14:09:01 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina&status=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina&status=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 113, in get
        for i in arg:
    RuntimeError: dictionary changed size during iteration
[E 190214 14:09:01 web:2162] 500 GET /api/v1/schedulers?spider=sina&status=1 (::1) 5613.57ms
[E 190214 14:36:31 web:1670] Uncaught exception GET /api/v1/schedulers?spider__icontains=sina&status=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__icontains=sina&status=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 120, in get
        filters[k] = value.decode('utf8')
    AttributeError: 'list' object has no attribute 'decode'
[E 190214 14:36:31 web:2162] 500 GET /api/v1/schedulers?spider__icontains=sina&status=1 (::1) 39023.92ms
[E 190214 14:40:16 web:1670] Uncaught exception GET /api/v1/schedulers?spider__ictains=sINa&status=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__ictains=sINa&status=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 124, in get
        res = await Schedulers.filter(**filters).limit(limit).order_by(ordering)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 433, in _execute
        self.query = self._make_query()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 421, in _make_query
        custom_filters=self._custom_filters,
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 27, in resolve_filters
        modifier &= node.resolve(model, annotations, custom_filters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 278, in resolve
        return self._resolve_kwargs(model)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 247, in _resolve_kwargs
        key, value = self._get_actual_filter_params(model, raw_key, raw_value)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 240, in _get_actual_filter_params
        allowed
    tortoise.exceptions.FieldError: Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
[E 190214 14:40:16 web:2162] 500 GET /api/v1/schedulers?spider__ictains=sINa&status=1 (::1) 8244.43ms
[E 190214 14:43:53 handler:126] Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
[E 190214 14:43:53 web:1670] Uncaught exception GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__ictains=sINa&status=1&limit=10', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 124, in get
        res = await Schedulers.filter(**filters).limit(limit).order_by(ordering)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 433, in _execute
        self.query = self._make_query()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 421, in _make_query
        custom_filters=self._custom_filters,
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 27, in resolve_filters
        modifier &= node.resolve(model, annotations, custom_filters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 278, in resolve
        return self._resolve_kwargs(model)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 247, in _resolve_kwargs
        key, value = self._get_actual_filter_params(model, raw_key, raw_value)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 240, in _get_actual_filter_params
        allowed
    tortoise.exceptions.FieldError: Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 127, in get
        finish_resp(400, error)
    TypeError: finish_resp() missing 1 required positional argument: 'message'
[E 190214 14:43:53 web:2162] 500 GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1) 26.52ms
[E 190214 14:44:05 handler:126] Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
[E 190214 14:44:05 web:1670] Uncaught exception GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__ictains=sINa&status=1&limit=10', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 124, in get
        res = await Schedulers.filter(**filters).limit(limit).order_by(ordering)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 433, in _execute
        self.query = self._make_query()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 421, in _make_query
        custom_filters=self._custom_filters,
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 27, in resolve_filters
        modifier &= node.resolve(model, annotations, custom_filters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 278, in resolve
        return self._resolve_kwargs(model)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 247, in _resolve_kwargs
        key, value = self._get_actual_filter_params(model, raw_key, raw_value)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/query_utils.py", line 240, in _get_actual_filter_params
        allowed
    tortoise.exceptions.FieldError: Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 127, in get
        finish_resp(self, 400, error)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 61, in finish_resp
        self.finish(message)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1025, in finish
        self.write(chunk)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 744, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 190214 14:44:05 web:2162] 500 GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1) 23.39ms
[E 190214 14:44:15 handler:126] Unknown filter param 'spider__ictains'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
[W 190214 14:44:15 web:2162] 400 GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1) 4.40ms
[E 190214 14:44:15 web:1670] Uncaught exception GET /api/v1/schedulers?spider__ictains=sINa&status=1&limit=10 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__ictains=sINa&status=1&limit=10', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 128, in get
        item = dict(count=len(res))
    UnboundLocalError: local variable 'res' referenced before assignment
[E 190214 14:46:07 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina&status=1&limit=10 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina&status=1&limit=10', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 115, in get
        ordering = filters.opo('ordering')
    AttributeError: 'dict' object has no attribute 'opo'
[E 190214 14:46:07 web:2162] 500 GET /api/v1/schedulers?spider=sina&status=1&limit=10 (::1) 45.37ms
[E 190214 14:46:22 web:1670] Uncaught exception GET /api/v1/schedulers?spider=sina&status=1&limit=10 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider=sina&status=1&limit=10', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 115, in get
        ordering = filters.pop('ordering')
    KeyError: 'ordering'
[E 190214 14:46:22 web:2162] 500 GET /api/v1/schedulers?spider=sina&status=1&limit=10 (::1) 13.41ms
[E 190214 14:52:18 handler:131] Unknown filter param 'spider_endswith'. Allowed base values are ['create_time', 'creator', 'id', 'ins', 'jid', 'job', 'mode', 'project', 'spider', 'status', 'timer', 'version']
[W 190214 14:52:18 web:2162] 400 GET /api/v1/schedulers?spider_endswith=u (::1) 9729.98ms
[E 190214 14:52:18 web:1670] Uncaught exception GET /api/v1/schedulers?spider_endswith=u (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider_endswith=u', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 133, in get
        item = dict(count=len(res))
    UnboundLocalError: local variable 'res' referenced before assignment
[E 190214 15:02:29 handler:104] 'NoneType' object is not subscriptable
[W 190214 15:02:29 web:2162] 400 GET /api/v1/schedulers?spider__endswith=u (::1) 7.61ms
[E 190214 15:02:29 web:1670] Uncaught exception GET /api/v1/schedulers?spider__endswith=u (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__endswith=u', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 106, in get
        item = dict(count=len(res))
    UnboundLocalError: local variable 'res' referenced before assignment
[E 190214 15:03:23 handler:112] 'NoneType' object is not subscriptable
[W 190214 15:03:23 web:2162] 400 GET /api/v1/schedulers?spider__endswith=u (::1) 9350.43ms
[E 190214 15:09:31 web:1670] Uncaught exception GET /api/v1/schedulers?spider__endswith=u&ordering= (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__endswith=u&ordering=', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 100, in get
        filters, limit, ordering = prep_filters(self.request.arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 121, in prep_filters
        del value['limit']
    KeyError: 'limit'
[E 190214 15:09:31 web:2162] 500 GET /api/v1/schedulers?spider__endswith=u&ordering= (::1) 33560.26ms
[E 190214 15:14:13 web:1670] Uncaught exception GET /api/v1/schedulers?spider__endswith=u&ordering= (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?spider__endswith=u&ordering=', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 100, in get
        filters, limit, ordering = prep_filters(self.request.arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 118, in prep_filters
        limit = value.get('limit')[0]
    TypeError: 'NoneType' object is not subscriptable
[E 190214 15:14:13 web:2162] 500 GET /api/v1/schedulers?spider__endswith=u&ordering= (::1) 25.78ms
[E 190214 15:20:49 handler:112] string index out of range
[W 190214 15:20:49 web:2162] 400 GET /api/v1/schedulers?spider__endswith=u&ordering= (::1) 63974.12ms
[E 190214 15:26:24 web:1670] Uncaught exception DELETE /api/v1/projects?id=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='DELETE', uri='/api/v1/projects?id=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 90, in delete
        await self.filestorage.delete(project, version)
    NameError: name 'project' is not defined
[E 190214 15:26:24 web:2162] 500 DELETE /api/v1/projects?id=1 (::1) 28003.66ms
[E 190214 15:29:16 web:1670] Uncaught exception DELETE /api/v1/projects?id=1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='DELETE', uri='/api/v1/projects?id=1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 91, in delete
        res = await Projects.delete(id=sid)
    TypeError: delete() got an unexpected keyword argument 'id'
[E 190214 15:29:16 web:2162] 500 DELETE /api/v1/projects?id=1 (::1) 3893.07ms
[W 190214 15:40:54 web:2162] 405 DELETE /api/v1/schedulers?ordering=-id (::1) 2.27ms
[E 190214 15:45:13 web:1670] Uncaught exception GET /api/v1/schedulers?ordering=-id (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?ordering=-id', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 100, in get
        order = arguments.order.raw_data
    AttributeError: 'SchedulersForm' object has no attribute 'order'
[E 190214 15:45:13 web:2162] 500 GET /api/v1/schedulers?ordering=-id (::1) 21.63ms
[E 190214 15:48:23 web:1670] Uncaught exception GET /api/v1/schedulers?ordering=-id (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?ordering=-id', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 102, in get
        aps = arguments.i.raw_data
    AttributeError: 'SchedulersForm' object has no attribute 'i'
[E 190214 15:48:23 web:2162] 500 GET /api/v1/schedulers?ordering=-id (::1) 4683.45ms
[E 190214 15:58:08 web:1670] Uncaught exception GET /api/v1/schedulers (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 102, in get
        if arguments[i].raw_data[0]:
    IndexError: list index out of range
[E 190214 15:58:08 web:2162] 500 GET /api/v1/schedulers (::1) 10.52ms
[E 190214 16:11:02 web:1670] Uncaught exception GET /api/v1/schedulers?mode=interval (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?mode=interval', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 103, in get
        for x in i:
    TypeError: 'Schedulers' object is not iterable
[E 190214 16:11:02 web:2162] 500 GET /api/v1/schedulers?mode=interval (::1) 17.35ms
[E 190214 16:15:01 web:1670] Uncaught exception GET /api/v1/schedulers?mode=interval (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?mode=interval', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 106, in get
        its[f] = i.f
    AttributeError: 'Schedulers' object has no attribute 'f'
[E 190214 16:15:01 web:2162] 500 GET /api/v1/schedulers?mode=interval (::1) 24.99ms
[E 190214 16:15:29 web:1670] Uncaught exception GET /api/v1/schedulers?mode=interval (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?mode=interval', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 106, in get
        its[f] = i[f]
    TypeError: 'Schedulers' object is not subscriptable
[E 190214 16:15:29 web:2162] 500 GET /api/v1/schedulers?mode=interval (::1) 13.44ms
[E 190214 16:17:10 web:1670] Uncaught exception GET /api/v1/schedulers?mode=interval (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?mode=interval', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 106, in get
        its[f] = i.get(f)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 292, in get
        return QuerySet(cls).get(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 344, in get
        queryset = self.filter(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 160, in filter
        return self._filter_or_exclude(negate=False, *args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/queryset.py", line 136, in _filter_or_exclude
        raise TypeError('expected Q objects as args')
    TypeError: expected Q objects as args
[E 190214 16:17:10 web:2162] 500 GET /api/v1/schedulers?mode=interval (::1) 3231.87ms
[E 190214 16:17:53 web:1670] Uncaught exception GET /api/v1/schedulers?mode=interval (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/schedulers?mode=interval', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 108, in get
        self.finish(item)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1025, in finish
        self.write(chunk)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 746, in write
        chunk = escape.json_encode(chunk)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/escape.py", line 81, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type datetime is not JSON serializable
[E 190214 16:17:53 web:2162] 500 GET /api/v1/schedulers?mode=interval (::1) 59.79ms
[W 190214 16:27:55 web:2162] 404 GET /api/v1/records (::1) 1.00ms
[E 190214 16:28:48 web:1670] Uncaught exception GET /api/v1/records (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/records', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/home/handler.py", line 151, in get
        query = await Records.filter(**params).limit(3, 5).order_by(ordering)
    TypeError: limit() takes 2 positional arguments but 3 were given
[E 190214 16:28:48 web:2162] 500 GET /api/v1/records (::1) 4.92ms
[E 190214 17:06:20 web:1670] Uncaught exception POST /api/v1/reg (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='POST', uri='/api/v1/reg', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 15, in post
        if not arguments.validate():
    AttributeError: 'User' object has no attribute 'validate'
[E 190214 17:06:20 web:2162] 500 POST /api/v1/reg (::1) 13.22ms
[E 190214 17:06:32 web:1670] Uncaught exception POST /api/v1/reg (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='POST', uri='/api/v1/reg', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 18, in post
        username = arguments.username.data
    AttributeError: 'NoneType' object has no attribute 'data'
[E 190214 17:06:32 web:2162] 500 POST /api/v1/reg (::1) 2.14ms
[E 190214 17:06:51 core:157] returning exception NOT NULL constraint failed: user.remark
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:06:51 web:1670] Uncaught exception POST /api/v1/reg (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='POST', uri='/api/v1/reg', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 21, in wrapped
        return await func(self, query, *args)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 86, in execute_insert
        return (await connection.execute_insert(query, values))[0]
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 216, in execute_insert
        return await self._execute(self._execute_insert, sql, parameters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
        return await future
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 33, in post
        await User.create(username=username, password=pwd, email=email, code=code, role=role)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 267, in create
        await instance.save(using_db=kwargs.get('using_db'))
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 211, in save
        await self._insert_instance(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 200, in _insert_instance
        ).execute_insert(self)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/base/executor.py", line 77, in execute_insert
        instance.id = await self.db.execute_insert(query, values)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 25, in wrapped
        raise IntegrityError(exc)
    tortoise.exceptions.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:06:51 web:2162] 500 POST /api/v1/reg (::1) 70.56ms
[E 190214 17:08:44 core:157] returning exception NOT NULL constraint failed: user.remark
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:08:44 web:1670] Uncaught exception POST /api/v1/reg (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='POST', uri='/api/v1/reg', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 21, in wrapped
        return await func(self, query, *args)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 86, in execute_insert
        return (await connection.execute_insert(query, values))[0]
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 216, in execute_insert
        return await self._execute(self._execute_insert, sql, parameters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
        return await future
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 33, in post
        await User.create(username=username, password=pwd, email=email, code=code, role=role)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 267, in create
        await instance.save(using_db=kwargs.get('using_db'))
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 211, in save
        await self._insert_instance(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 200, in _insert_instance
        ).execute_insert(self)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/base/executor.py", line 77, in execute_insert
        instance.id = await self.db.execute_insert(query, values)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 25, in wrapped
        raise IntegrityError(exc)
    tortoise.exceptions.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:08:44 web:2162] 500 POST /api/v1/reg (::1) 14.58ms
[E 190214 17:09:09 core:157] returning exception NOT NULL constraint failed: user.remark
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:09:09 web:1670] Uncaught exception POST /api/v1/reg (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='POST', uri='/api/v1/reg', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 21, in wrapped
        return await func(self, query, *args)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 86, in execute_insert
        return (await connection.execute_insert(query, values))[0]
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 216, in execute_insert
        return await self._execute(self._execute_insert, sql, parameters)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 167, in _execute
        return await future
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 153, in run
        result = function()
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/aiosqlite/core.py", line 133, in _execute_insert
        cursor = self._conn.execute(sql, parameters)
    sqlite3.IntegrityError: NOT NULL constraint failed: user.remark
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 33, in post
        await User.create(username=username, password=pwd, email=email, code=code, role=role)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 267, in create
        await instance.save(using_db=kwargs.get('using_db'))
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 211, in save
        await self._insert_instance(*args, **kwargs)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/models.py", line 200, in _insert_instance
        ).execute_insert(self)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/base/executor.py", line 77, in execute_insert
        instance.id = await self.db.execute_insert(query, values)
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tortoise/backends/sqlite/client.py", line 25, in wrapped
        raise IntegrityError(exc)
    tortoise.exceptions.IntegrityError: NOT NULL constraint failed: user.remark
[E 190214 17:09:09 web:2162] 500 POST /api/v1/reg (::1) 47.20ms
[W 190214 17:10:55 web:2162] 405 GET /api/v1/reg (::1) 5.53ms
[E 190214 17:12:14 web:1670] Uncaught exception GET /api/v1/user (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/user', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 72, in get
        params, offset, limit, ordering = prep_params(arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 124, in prep_params
        ordering = params.pop('ordering')
    KeyError: 'ordering'
[E 190214 17:12:14 web:2162] 500 GET /api/v1/user (::1) 5.36ms
[E 190214 17:14:13 web:1670] Uncaught exception GET /api/v1/user (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/user', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 72, in get
        params, offset, limit, ordering = prep_params(arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 126, in prep_params
        offset = params.pop('offset')
    KeyError: 'offset'
[E 190214 17:14:13 web:2162] 500 GET /api/v1/user (::1) 14.04ms
[E 190214 17:14:44 web:1670] Uncaught exception GET /api/v1/user (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/user', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 72, in get
        params, offset, limit, ordering = prep_params(arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 126, in prep_params
        offset = params.pop('offset')
    KeyError: 'offset'
[E 190214 17:14:44 web:2162] 500 GET /api/v1/user (::1) 21.05ms
[E 190214 17:15:32 web:1670] Uncaught exception GET /api/v1/user (::1)
    HTTPServerRequest(protocol='http', host='localhost:8205', method='GET', uri='/api/v1/user', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/gannicus/anaconda3/envs/envpoll/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/admin/handler.py", line 72, in get
        params, offset, limit, ordering = prep_params(arguments)
      File "/home/gannicus/github/AsyncIns/AsyncIns/component/common/util.py", line 126, in prep_params
        offset = params.pop('offset')
    KeyError: 'offset'
[E 190214 17:15:32 web:2162] 500 GET /api/v1/user (::1) 15.83ms
